string="INDIA"
print(string.isalnum())

str1="abc123"
str2="12345"
str3="india"
print(str2.format())
print(str3.capitalize())
print(string.casefold())
print(str3.count('i'))
print(str1.endswith('i'))
print(str3.expandtabs())
print(str3.format_map('d'));
print(str3.index('n'))
print(str1.isalpha())
print(str1.isdecimal())
print(str1.isdigit())
print(str3.islower())
print(str3.isnumeric())
print(str3.isupper())
